### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by thnee**

### CODE REVIEW

**Comment by thnee** [comment]
@gilsondev Looks like the build for python 3.3 is failing because Django 1.9 started using something called `find_spec` which was introduced first in Python 3.4.

Here is a commit on another repo that seems to solve this exact thing: https://github.com/pinax/pinax-blog/issues/68

But they are specifying the Django versions in the `env` setting in the `.travis.yml`, which this project is not doing. Would you agree to use that way of defining this setting instead?

**Comment by gilsondev** [comment]
Yes, its a good idea.

**Comment by gilsondev** [comment]
So, we are remove the `.travis.yml` the tests with Python 3.3, e verify only this versions:
- Python 2.7
- Python 3.4
- Python 3.5

What do you think?

**Comment by thnee** [comment]
100% OK with me!

**Comment by gilsondev** [comment]
Travis changed.

**Comment by thnee** [comment]
@gilsondev Excellent, thanks, now the build passes. Ready for review.

**Pull request merged**
